name: Flatpak

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - name: Install deps
        if: ${{ matrix.arch != 'x86_64' }}
        run: |
          dnf -y install docker
  
      - name: Set up QEMU
        if: ${{ matrix.arch != 'x86_64' }}
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
  
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: nxdumpclient.flatpak
          manifest-path: flatpak/org.v1993.NXDumpClient.yml
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Rename files appropriately
        shell: bash
        run: |
          mkdir upload
          find artifacts -mindepth 1 -type d -exec sh -c 'cp "$0"/nxdumpclient.flatpak upload/$(basename "$0").flatpak' {} \;
          echo "Files to upload:"
          find upload -type f -printf '%f\n'

      - name: Upload flatpaks to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: upload/*
